FLASK/view/APP/models.py
from app import db 

from datetime import datetime
import re

def slugify(s):
	pattern = r'[^\w+]'
	return re.sub(pattern,'-',s)


post_tags = db.Table('post_tags',
					 db.Column('post_id',db.Integer, db.ForeignKey('post.id')),
					 db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
	)




class Post(db.Model):
	id = db.Column(db.Integer, primary_key = True)
	title = db.Column(db.String(140))
	slug = db.Column(db.String(140), unique = True)
	body = db.Column(db.Text)
	created = db.Column(db.DateTime, default=datetime.now())


	def __init__(self,*args, **kwargs):
		super(Post, self).__init__(*args,**kwargs)
		self.generate_slug()


	tags = db.relationship('Tag', secondary = post_tags, backref=db.backref('posts', lazy='dynamic'))




	def generate_slug(self):
		if self.title:
			self.slug = slugify(self.title)

	def __repr__(self):
		return '<Post id:{}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
	id = db.Column(db.Integer,primary_key=True)
	name = db.Column(db.String(100))
	slug = db.Column(db.String(100))

	def __init__(self, *args, **kwargs):
		super(Tag, self).__init__(*args,**kwargs)
		self.slug = slugify(self.name)

	def __repr__(self):
		return '<Tag id:{}, name: {}>'.format(self.id,self.name)

FLASK/view/APP/app.py
from flask import Flask
from config import Configuration
from flask_migrate import Migrate, MigrateCommand
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
 


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)

manager.add_command('db', MigrateCommand)




FLASK/view/APP/main.py
from app import app
import view
from posts.blueprint import posts
from app import db

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
	app.run()

FLASK/view/APP/posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post


posts = Blueprint('posts', __name__ , template_folder='templates')

@posts.route('/')
def index():
	posts = Post.query.all()
	return render_template('posts/index.html',posts=posts)

#http://localhost/blog/first-post
@posts.route('/<slug>')
def post_detail(slug):
	post = Post.query.filter(Post.slug==slug).first()
	return render_template('posts/post_detail.html',post=post)

FLASK/view/APP/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
	Blueprint index page
{% endblock %}

{% block content_title %}
	Postss
{% endblock %}

{% block content %}
	{% for post in posts %}

	
		<div class="post">
		
			<div class="title"><strong><em><a href="{{url_for('posts.post_detail',slug=post.slug)}}" style="text-decoration: none;color: black">{{post.title}}</a></em></strong></div>
			<br>
		
			<div class="body">{{post.body}}</div>
			<div class="datetime">{{post.created}}</div>


		</div>



	{% endfor %}

{% endblock %}

FLASK/view/APP/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
	{{post.title}}
{% endblock %}

{% block content_title %}
	{{post.title}}
{% endblock %}

{% block content %}

	<div class="detail">
		<h2>{{post.title}}</h2>
		<h3>{{post.body}}</h3>
	</div>


{% endblock %}

FLASK/view/APP/templates/base.html
<!DOCTYPE html>
<html>
<head>
	
	<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
	<title>
			{% block title %}

			{% endblock %} | Flask app
	</title>
</head>
<body>

<div class="contain">
<ul>
  <li id ='tab'><a href=" {{ url_for('index') }}">Flask</a></li>
  <li id ='tab'><a href="{{ url_for('posts.index')}}">Blog</a></li>
  <li id ='tab'><a href="#">Link</a></li>
  <li id='search'><input type="text" name="s"></li>
  <li class="sign" id='tab'><a href="">Sign up</a></li>
  <li class="sign" id="tab"><a href="">Sign in</a></li>
</ul>

	
</div>


<!-- <h2>{% block content_title  %}
	{% endblock  %}</h2>  -->
<div class="content">

	{% block content   %}

	{% endblock  %}
</div>



</body>
</html>

FLASK/view/APP/templates/index.html
{% extends 'base.html' %}

{% block title %}

	index page

{% endblock %}

{% block content_title %}

	index page

{% endblock %}

{% block content %}

	some content

{% endblock %}